export const types = {

    ADD_TASK: 'ADD_TASK',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_ERROR: 'ADD_TASK_ERROR',

    GET_TASKS: 'GET_TASKS',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_tASKS_ERROR: 'GET_tASKS_ERROR',

    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',

    GET_TASK_TO_DELETE: 'GET_TASK_TO_DELETE',
    DELETED_TASK_SUCCESS: 'DELETED_TASK_SUCCESS',
    DELETED_TASK_ERROR: 'DELETED_TASK_ERROR',

    GET_TASK_TO_UPDATE: 'GET_TASK_TO_UPDATE',
    EDIT_TASK: 'EDIT_TASK',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_ERROR: 'EDIT_TASK_ERROR'

}
